#!/usr/bin/env node
const fs = require('fs');
const os = require('os');
const promisify = require('util').promisify;
const readDir = promisify(fs.readdir);

async function main() {
  const dest = `${os.homedir()}/.tsrabbit`;
  console.log({ dest });
  const dirExists = fs.existsSync(dest);
  if (dirExists) {
    fs.rmSync(dest, { recursive: true, force: true });
  }
  fs.mkdirSync(dest);
  const files = await readDir('./bin');
  await Promise.all(
    files.map((file) => {
      fs.writeFileSync(`${dest}/${file}`, '');
      fs.copyFileSync(`./bin/${file}`, `${dest}/${file}`);
    })
  );
}

main();
